services:
  mysql:
    image: mysql:${DOCKER_MYSQL_VERSION:-latest}
    container_name: ${DOCKER_MYSQL_CONTAINER_NAME:-mysql_container}
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?error}
      MYSQL_DATABASE: ${MYSQL_DATABASE:?error}
      MYSQL_USER: ${MYSQL_USER:?error}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?error}
    ports:
      - '${MYSQL_PORT:-3306}:3306'
      - '${MYSQL_XPORT:-33060}:33060'
    volumes:
      - mysql_data:/var/lib/mysql:rw
    user: root
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 10s
      retries: 3

  redis:
    image: redis:${DOCKER_REDIS_VERSION}
    container_name: ${DOCKER_REDIS_CONTAINER_NAME}
    env_file: .env
    ports: ['${REDIS_PORT}:6379']
    volumes: [redis_data:/data:rw]
    user: ${UID}:${GID}
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_MYSQL_DATA_DIR:-./data/db}

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_REDIS_DATA_DIR:-./data/redis}
