# Description: Docker compose template for storage services

services:
  nginx:
    image: nginx:${DOCKER_NGINX_VERSION:-latest}
    container_name: ${DOCKER_NGINX_CONTAINER_NAME:-nginx_template}
    ports:
      - 80:80
    volumes:
      - ./deps/nginx/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    image: mysql:${DOCKER_MYSQL_VERSION:-latest}
    container_name: ${DOCKER_MYSQL_CONTAINER_NAME:-mysql_template}
    restart: 'on-failure:1'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 10s
      retries: 3

  redis:
    image: redis:${DOCKER_REDIS_VERSION:-latest}
    container_name: ${DOCKER_REDIS_CONTAINER_NAME:-redis_template}
    restart: 'on-failure:1'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 10s
      retries: 3
